server:
  port: 8889

spring:
  datasource:
    name: depot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mybatis.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql